# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  # Node.js dependencies in GitHub Actions
  - package-ecosystem: npm
    directory: /.github/actions/codex
    schedule:
      interval: weekly
  # Rust dependencies
  - package-ecosystem: cargo
    directory: /codex-rs
    schedule:
      interval: weekly
  # Dev containers
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
  # Docker dependencies
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
