services:
  codex:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/codex-cli:latest
    container_name: codex-cli
    environment:
      # Preferred ChatGPT auth stored in mounted ~/.codex/auth.json
      - CODEX_HOME=/home/node/.codex
      - RUST_LOG=codex_core=info,codex_tui=info
      # OpenAI API key from environment (CI)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Persist Codex home (auth.json, config.toml, logs) inside project tree
      - ./volumes/codex_home:/home/node/.codex
      # Workspace bind-mount for live development of tools/runners/agents
      - ./volumes/workspace:/workspace
      # Optional: mount your repositories or tools under ./volumes/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    # Network is host-like for local dev; lock down in prod as needed
    # network_mode: host  # optional; comment out if not desired
    ports:
      - "1455:1455"   # for login helper (browser auth callback)

# Named volumes are not used so everything stays inside this directory
