name: CI
on:
  push:
  pull_request:
jobs:
  build-and-self-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build containers
        run: docker compose -f docker-compose.yaml build
      - name: Start stack
        run: docker compose -f docker-compose.yaml up -d
      - name: Self-check
        run: bin/self-check.sh
      - name: Teardown
        if: always()
        run: docker compose -f docker-compose.yaml down -v
